// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20260206154706_AddVisitorsTable")]
    partial class AddVisitorsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("backend.models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("backend.models.Visitor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("contactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("contacted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("joined")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("visitedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("backend.models.members", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("bagProvided")
                        .HasColumnType("INTEGER");

                    b.Property<string>("contactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("due")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("memberSince")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("paid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("payment")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("subscriptionExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("subscriptionPlan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("subscriptionStartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
